---
packages:
  # - python-httplib2         # required for calling Ambari API from Ansible
  # - libselinux-python 
  - curl                    # curl required by Ambari
  - unzip                   # unzip required by Ambari
  - tar                     # tar required by Ambari
  - wget                    # wget required by Ambari
  - openssl                 # openssl required by Ambari
  # - chrony                  # ntp required by Hadoop
  - ntp
  - krb5-workstation
  - krb5-libs
  - krb5-devel
  - openldap-clients
  - yum-utils
  - libselinux-python

# ntp_service_name: chronyd

ntp_service_name: ntpd

firewall_service_name: firewalld

epel_url: "http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
