---
- name: Load variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family|lower }}.yml"
        - defaults.yml
      paths:
        - ../vars

# - name: Download the Ambari repository definition
#   get_url:
#     url: "{{ ambari_repo_url }}"
#     dest: "{{ ambari_repo_destination }}"
#     force: yes

- name: Add Ambari local repo file in yum.repos.d
  yum_repository:
    name: '{{ local.ambari_repo_name }}'
    description: '{{ local.ambari_repo_desc }}'
    baseurl: '{{ local.ambari_repo_url }}'
    gpgcheck: no


# - name: Add HDP repo file in yum
#   yum_repository:
#     name: '{{ local_hdp_repo_name }}'
#     description: '{{ local_hdp_repo_desc }}'
#     baseurl: '{{ local_hdp_repo_url }}'
#     gpgcheck: no
#   when: install_hdp is defined and install_hdp


# - name: Add HDP-UTILS repo file in yum
#   yum_repository:
#     name: '{{ local_hdputils_repo_name }}'
#     description: '{{ local_hdputils_repo_desc }}'
#     baseurl: '{{ local_hdputils_repo_url }}'
#     gpgcheck: no


# - name: Add HDF repo file in yum
#   yum_repository:
#     name: '{{ local_hdf_repo_name }}'
#     description: '{{ local_hdf_repo_desc }}'
#     baseurl: '{{ local_hdf_repo_url }}'
#     gpgcheck: no
#   when: install_hdf is defined and install_hdf