---
- name: Reload systemd
  command: systemctl daemon-reload
  when: (ansible_os_family|lower == "redhat" and ansible_distribution_major_version|int == 7)

- name: Restart cloudera-scm-agent
  service: name=cloudera-scm-agent state=restarted