---
mysql_packages:
  - MySQL-python
  - mysql-connector-java
mysql_jdbc_location: /usr/share/java/mysql-connector-java.jar

mariadb_packages:
  - MySQL-python
  - mysql-connector-java
mariadb_jdbc_location: /usr/share/java/mysql-connector-java.jar
