
---
# - include: "set_variables.yml"

###############################################################
#############     Prepare the Nodes        ####################
###############################################################

- name: Prepare Nodes
  hosts: all
  user: '{{ user }}'
  #become: yes
  #become_method: sudo
  roles:
    - prepare-cluster-nodes
  tags: prepareclusternodes


###############################################################
#############          Setup Database     #####################
###############################################################

- name: Setup {{ database }} role Database node
  hosts: cloudera-server
  user: '{{ user }}'
  any_errors_fatal: true
  become: yes
  roles:
    - role: setup-cluster-database
      when: database != "embedded" or database != "oracle" and not database_options.external_hostname|default('')
  tags: setupdatabase


###############################################################
############# Install cloudera Server ##############
###############################################################

- name: Intall cloudera Server
  hosts: cloudera-server
  user: '{{ user }}'
  any_errors_fatal: true
  #become: yes
  #become_method: sudo
  roles:
    - install-cloudera-server
  tags: installclouderaserver


###############################################################
############# Configure cloudera Server ###########################
###############################################################

- name: Configure cloudera Server
  hosts: cloudera-server
  user: '{{ user }}'
  any_errors_fatal: true
  #become: yes
  #become_method: sudo
  roles:
    - configure-cloudera-server
  tags: configureclouderaserver

###############################################################
############# Install cloudera Agents on the nodes ##############
###############################################################

- name: Intall cloudera Agents on the nodes
  hosts: all
  user: '{{ user }}'
  any_errors_fatal: true
  #become: yes
  #become_method: sudo
  roles:
    - install-cloudera-agents
  tags: installclouderaagents


####################################################
#### Start or Stop cloudera server or agents##########
####################################################

- name: Stop cloudera Server
  hosts: cloudera-server
  user: '{{ user }}'
  #become: yes
  #become_method: sudo
  gather_facts: no
  roles:
    - stop-cloudera-server
  tags: stopclouderaserver

- name: Stop cloudera Agents
  hosts: all
  user: '{{ user }}'
  #become: yes
  #become_method: sudo
  gather_facts: no
  roles:
    - stop-cloudera-agents
  tags: stopclouderaagents

- name: Start cloudera Server
  hosts: cloudera-server
  user: '{{ user }}'
  #become: yes
  #become_method: sudo
  gather_facts: no
  roles:
    - start-cloudera-server
  tags: startclouderaserver


- name: Start cloudera Agents
  hosts: all
  user: '{{ user }}'
  #become: yes
  #become_method: sudo
  gather_facts: no
  roles:
    - start-cloudera-agents
  tags: startclouderaagents
